[versions]
agp = "8.13.2"
fragmentKtx = "1.8.9"
glide = "5.0.5"
gson = "2.13.2"
kotlin = "2.3.0"
lifecycleViewmodelKtx = "2.10.0"
material = "1.13.0"
photoview = "2.3.0"
roomRuntime = "2.8.4"
swiperefreshlayout = "1.2.0"
textRecognition = "16.0.1"

[libraries]
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
material = { module = "com.google.android.material:material", version.ref = "material" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "textRecognition" }
text-recognition-chinese = { module = "com.google.mlkit:text-recognition-chinese", version.ref = "textRecognition" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin" }

